# Generated by Django 4.2.6 on 2023-10-26 14:57

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
