# Generated by Django 4.2.6 on 2023-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231026_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='userItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('image_s', models.URLField(blank=True, null=True)),
                ('image_m', models.URLField(blank=True, null=True)),
                ('image_l', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
