# Generated by Django 4.2.6 on 2023-10-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.TextField(blank=True, null=True),
        ),
    ]
