# Generated by Django 4.2.6 on 2023-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_review_key_alter_review_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
