name: Run Tests

on:
    pull_request:
    push:
        branches:
        - main

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout sources
            uses: actions/checkout@v3

          - name: Setup python 3.10.6
            uses: actions/setup-python@v4
            with:
                python-version: '3.10.6'

          - name: Install dependencies
            run: pip install -r requirements.txt

          - name: Run unit tests
            run: python manage.py test